#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Run the TRACE cleaning-clustering pipeline.

This runner reads results/eigenvectors.json, runs selected cleaners and
clusterers, and writes the original pipeline outputs:

- results/cleaned_results.json
- results/clustered_results.json
- results/analyzed_results.json
- results/logs/pipeline_run_manifest.json
- results/logs/pipeline_failures.json
- results/cleaned_data/
- results/clustered_data/

Stage 2.6 change:
- Cleaner and clusterer selection is resolved from configs/methods.yaml.
- TRACE-native method ids are 0-based for both cleaners and clusterers.
- legacy_id is preserved for compatibility with the original pipeline and
  archived raw results.

Examples:
    python -m src.pipeline.runner --cleaners mode --clusterers HC
    python -m src.pipeline.runner --cleaners 0 --clusterers 0
    python -m src.pipeline.runner --cleaners legacy:1 --clusterers legacy:0
    python -m src.pipeline.runner --cleaners group:smoke --clusterers group:full
"""

from __future__ import annotations

import argparse
import inspect
import json
import multiprocessing as mp
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional


PROJECT_ROOT = Path(
    os.environ.get("TRACE_PROJECT_ROOT", Path(__file__).resolve().parents[2])
).resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.pipeline.analysis import save_analyzed_results
from src.pipeline.cleaning_runner import run_error_correction
from src.pipeline.clustering_runner import run_clustering
from src.pipeline.method_registry import MethodRegistry, MethodSpec


RuntimeSpec = dict[str, Any]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the TRACE cleaning-clustering pipeline."
    )

    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="TRACE repository root. Default: auto-detected root.",
    )
    parser.add_argument(
        "--methods-config",
        type=Path,
        default=None,
        help="Method registry YAML. Default: <project-root>/configs/methods.yaml.",
    )
    parser.add_argument(
        "--eigenvectors",
        type=Path,
        default=PROJECT_ROOT / "results" / "eigenvectors.json",
        help="Input eigenvectors JSON generated by src.pipeline.preprocess.",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=PROJECT_ROOT / "results",
        help="Directory for original pipeline outputs.",
    )
    parser.add_argument(
        "--cleaned-results",
        type=Path,
        default=None,
        help="Output path for cleaned_results.json. Default: <results-dir>/cleaned_results.json.",
    )
    parser.add_argument(
        "--clustered-results",
        type=Path,
        default=None,
        help="Output path for clustered_results.json. Default: <results-dir>/clustered_results.json.",
    )
    parser.add_argument(
        "--analyzed-results",
        type=Path,
        default=None,
        help="Output path for analyzed_results.json. Default: <results-dir>/analyzed_results.json.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Output path for pipeline_run_manifest.json. Default: <results-dir>/logs/pipeline_run_manifest.json.",
    )
    parser.add_argument(
        "--max-records",
        type=int,
        default=None,
        help="Limit the number of eigenvector records. Use 1 for Mode B smoke tests.",
    )
    parser.add_argument(
        "--record-offset",
        type=int,
        default=0,
        help="Skip the first N eigenvector records before applying --max-records.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=2,
        help="Number of parallel worker processes.",
    )
    parser.add_argument(
        "--cleaners",
        nargs="*",
        default=None,
        help=(
            "Cleaner subset resolved by configs/methods.yaml. Accepts TRACE ids, "
            "method names, aliases, legacy:<id>, or groups such as group:smoke. "
            "Default: all enabled cleaners."
        ),
    )
    parser.add_argument(
        "--clusterers",
        nargs="*",
        default=None,
        help=(
            "Clusterer subset resolved by configs/methods.yaml. Accepts TRACE ids, "
            "method names, aliases, legacy:<id>, or groups such as group:full. "
            "Default: all enabled clusterers."
        ),
    )
    parser.add_argument(
        "--cluster-trials",
        type=int,
        default=None,
        help=(
            "Optional Optuna trial budget for clustering scripts that support "
            "TRACE_N_TRIALS. Use a small value such as 5 for smoke tests. "
            "Default: clustering scripts use their own full budget."
        ),
    )
    parser.add_argument(
        "--clean-state",
        default="cleaned",
        help="State label passed to clustering scripts. Default: cleaned.",
    )
    parser.add_argument(
        "--skip-analysis",
        action="store_true",
        help="Skip clustered-result analysis.",
    )
    parser.add_argument(
        "--fail-fast",
        action="store_true",
        help="Stop after the first cleaner or clusterer failure.",
    )

    return parser.parse_args()


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)


def method_registry_path(project_root: Path, methods_config: Optional[Path]) -> Path:
    if methods_config is None:
        return project_root / "configs" / "methods.yaml"

    if methods_config.is_absolute():
        return methods_config

    return project_root / methods_config


def load_registry(project_root: Path, methods_config: Optional[Path]) -> MethodRegistry:
    registry_path = method_registry_path(project_root, methods_config)
    return MethodRegistry(registry_path)


def spec_to_runtime_dict(spec: MethodSpec) -> RuntimeSpec:
    """
    Convert MethodSpec to a plain dict.

    Plain dicts are safe to pass through ProcessPoolExecutor with spawn.
    """
    return {
        "kind": spec.kind,
        "name": spec.name,
        "id": spec.id,
        "legacy_id": spec.legacy_id,
        "display_name": spec.display_name,
        "enabled": spec.enabled,
        "group": spec.group,
        "implementation": spec.implementation,
        "output_contract": spec.output_contract,
        "default_env": spec.default_env,
        "raw": dict(spec.raw),
    }


def resolve_runtime_specs(
    registry: MethodRegistry,
    kind: str,
    tokens: Optional[Iterable[str]],
) -> list[RuntimeSpec]:
    specs = registry.resolve(kind, tokens)
    return [spec_to_runtime_dict(spec) for spec in specs]


def build_record_items(
    all_records: list[dict],
    record_offset: int,
    max_records: Optional[int],
) -> list[tuple[int, dict]]:
    """
    Build (dataset_id, record) pairs.

    dataset_id follows the original index in eigenvectors.json. This avoids
    changing output names when --record-offset is used.
    """
    record_items = list(enumerate(all_records))

    if record_offset > 0:
        record_items = record_items[record_offset:]

    if max_records is not None:
        record_items = record_items[:max_records]

    return record_items


def run_clustering_compat(
    *,
    dataset_id: int,
    cleaner_name: str,
    cluster_method_legacy_id: int,
    cleaned_file_path: str,
    root: Path,
    result_root: Path,
    cluster_trials: Optional[int],
    clean_state: str,
) -> tuple[Optional[str], Optional[float]]:
    """
    Call run_clustering while remaining compatible with older function versions.

    Newer clustering_runner.run_clustering accepts cluster_trials and clean_state.
    This wrapper also sets environment variables as a fallback.
    """
    old_trial_env = os.environ.get("TRACE_N_TRIALS")
    old_state_env = os.environ.get("CLEAN_STATE")

    if cluster_trials is not None:
        os.environ["TRACE_N_TRIALS"] = str(int(cluster_trials))
    if clean_state:
        os.environ["CLEAN_STATE"] = clean_state

    try:
        signature = inspect.signature(run_clustering)

        kwargs = {
            "dataset_id": dataset_id,
            "algorithm": cleaner_name,
            "cluster_method_id": cluster_method_legacy_id,
            "cleaned_file_path": cleaned_file_path,
            "project_root": root,
            "results_dir": result_root,
        }

        if "cluster_trials" in signature.parameters:
            kwargs["cluster_trials"] = cluster_trials
        if "clean_state" in signature.parameters:
            kwargs["clean_state"] = clean_state

        return run_clustering(**kwargs)

    finally:
        if old_trial_env is None:
            os.environ.pop("TRACE_N_TRIALS", None)
        else:
            os.environ["TRACE_N_TRIALS"] = old_trial_env

        if old_state_env is None:
            os.environ.pop("CLEAN_STATE", None)
        else:
            os.environ["CLEAN_STATE"] = old_state_env


def process_record(
    record_idx: int,
    record: dict,
    project_root: str,
    results_dir: str,
    cleaner_specs: list[RuntimeSpec],
    clusterer_specs: list[RuntimeSpec],
    cluster_trials: Optional[int] = None,
    clean_state: str = "cleaned",
    fail_fast: bool = False,
) -> tuple[list[dict], list[dict], list[dict]]:
    """
    Process one eigenvector record.

    This function is intentionally top-level so that ProcessPoolExecutor with
    spawn context can import it safely.
    """
    root = Path(project_root).resolve()
    result_root = Path(results_dir).resolve()

    cleaned_results: list[dict] = []
    clustered_results: list[dict] = []
    failures: list[dict] = []

    dataset_id = int(record_idx)
    dataset_name = str(record["dataset_name"])
    csv_file = str(record["csv_file"])
    error_rate = float(record["error_rate"])

    print(
        "[INFO] Processing record: "
        f"dataset_id={dataset_id}, dataset={dataset_name}, "
        f"csv={csv_file}, error_rate={error_rate:.4f}%"
    )

    # Keep the original skip condition for compatibility.
    if abs(error_rate - 0.01) < 1e-12:
        print(f"[INFO] Detected clean-like record for {dataset_name}; skip.")
        print("=" * 50)
        return cleaned_results, clustered_results, failures

    dataset_folder = root / "datasets" / "train" / dataset_name
    dirty_csv_path = dataset_folder / csv_file
    clean_csv_path = dataset_folder / "clean.csv"

    if not dirty_csv_path.exists() or not clean_csv_path.exists():
        message = f"Missing dataset files for {dataset_name}/{csv_file}."
        print(f"[WARN] {message}")
        print(f"[WARN] Dirty path: {dirty_csv_path}")
        print(f"[WARN] Clean path: {clean_csv_path}")

        failures.append(
            {
                "stage": "input",
                "dataset_id": dataset_id,
                "dataset_name": dataset_name,
                "csv_file": csv_file,
                "message": message,
            }
        )
        return cleaned_results, clustered_results, failures

    for cleaner_spec in cleaner_specs:
        cleaner_name = str(cleaner_spec["name"])
        cleaner_trace_id = int(cleaner_spec["id"])
        cleaner_legacy_id = int(cleaner_spec["legacy_id"])

        print(
            "[INFO] Running cleaner: "
            f"name={cleaner_name}, trace_id={cleaner_trace_id}, "
            f"legacy_id={cleaner_legacy_id}"
        )

        cleaned_file_path, cleaning_runtime = run_error_correction(
            dataset_path=str(dirty_csv_path),
            dataset_id=dataset_id,
            algorithm_id=cleaner_legacy_id,
            clean_csv_path=str(clean_csv_path),
            output_dir=str(result_root / dataset_name / cleaner_name),
            project_root=root,
            results_dir=result_root,
        )

        if cleaned_file_path is None or cleaning_runtime is None:
            message = (
                "Cleaner failed: "
                f"name={cleaner_name}, trace_id={cleaner_trace_id}, "
                f"legacy_id={cleaner_legacy_id}"
            )
            print(f"[ERROR] {message}")

            failures.append(
                {
                    "stage": "cleaning",
                    "dataset_id": dataset_id,
                    "dataset_name": dataset_name,
                    "csv_file": csv_file,
                    "cleaner_name": cleaner_name,
                    "cleaner_id": cleaner_trace_id,
                    "cleaner_legacy_id": cleaner_legacy_id,
                    "message": message,
                }
            )

            if fail_fast:
                raise RuntimeError(message)

            print("=" * 50)
            continue

        print(f"[INFO] Cleaning completed: dataset={dataset_name}, cleaner={cleaner_name}")
        print(f"[INFO] Cleaned file: {cleaned_file_path}")
        print(f"[INFO] Cleaning runtime: {cleaning_runtime:.2f}s")

        cleaned_results.append(
            {
                "dataset_id": dataset_id,
                "dataset_name": dataset_name,
                "csv_file": csv_file,
                "algorithm": cleaner_name,
                "algorithm_id": cleaner_trace_id,
                "algorithm_legacy_id": cleaner_legacy_id,
                "algorithm_display_name": cleaner_spec.get("display_name"),
                "cleaned_file_path": cleaned_file_path,
                "runtime": cleaning_runtime,
            }
        )

        for clusterer_spec in clusterer_specs:
            clusterer_name = str(clusterer_spec["name"])
            clusterer_trace_id = int(clusterer_spec["id"])
            clusterer_legacy_id = int(clusterer_spec["legacy_id"])

            cluster_output_dir, cluster_runtime = run_clustering_compat(
                dataset_id=dataset_id,
                cleaner_name=cleaner_name,
                cluster_method_legacy_id=clusterer_legacy_id,
                cleaned_file_path=cleaned_file_path,
                root=root,
                result_root=result_root,
                cluster_trials=cluster_trials,
                clean_state=clean_state,
            )

            if cluster_output_dir is None or cluster_runtime is None:
                message = (
                    "Clustering failed: "
                    f"name={clusterer_name}, trace_id={clusterer_trace_id}, "
                    f"legacy_id={clusterer_legacy_id}"
                )
                print(f"[ERROR] {message}")

                failures.append(
                    {
                        "stage": "clustering",
                        "dataset_id": dataset_id,
                        "dataset_name": dataset_name,
                        "csv_file": csv_file,
                        "cleaner_name": cleaner_name,
                        "cleaner_id": cleaner_trace_id,
                        "cleaner_legacy_id": cleaner_legacy_id,
                        "clusterer_name": clusterer_name,
                        "clusterer_id": clusterer_trace_id,
                        "clusterer_legacy_id": clusterer_legacy_id,
                        "message": message,
                    }
                )

                if fail_fast:
                    raise RuntimeError(message)

                continue

            clustered_results.append(
                {
                    "dataset_id": dataset_id,
                    "dataset_name": dataset_name,
                    "csv_file": csv_file,
                    "cleaning_algorithm": cleaner_name,
                    "cleaning_algorithm_id": cleaner_trace_id,
                    "cleaning_algorithm_legacy_id": cleaner_legacy_id,
                    "cleaning_runtime": cleaning_runtime,
                    "clustering_algorithm": clusterer_trace_id,
                    "clustering_algorithm_legacy_id": clusterer_legacy_id,
                    "clustering_name": clusterer_name,
                    "clustering_display_name": clusterer_spec.get("display_name"),
                    "clustering_runtime": cluster_runtime,
                    "clustered_file_path": cluster_output_dir,
                }
            )

            print(
                "[INFO] Clustering completed: "
                f"method={clusterer_name}, runtime={cluster_runtime:.2f}s"
            )

        print("=" * 50)

    return cleaned_results, clustered_results, failures


def run_records(
    record_items: list[tuple[int, dict]],
    project_root: Path,
    results_dir: Path,
    cleaner_specs: list[RuntimeSpec],
    clusterer_specs: list[RuntimeSpec],
    cluster_trials: Optional[int],
    clean_state: str,
    workers: int,
    fail_fast: bool,
) -> tuple[list[dict], list[dict], list[dict]]:
    cleaned_results: list[dict] = []
    clustered_results: list[dict] = []
    failures: list[dict] = []

    if workers == 1:
        for record_idx, record in record_items:
            result_cleaned, result_clustered, result_failures = process_record(
                record_idx=record_idx,
                record=record,
                project_root=str(project_root),
                results_dir=str(results_dir),
                cleaner_specs=cleaner_specs,
                clusterer_specs=clusterer_specs,
                cluster_trials=cluster_trials,
                clean_state=clean_state,
                fail_fast=fail_fast,
            )
            cleaned_results.extend(result_cleaned)
            clustered_results.extend(result_clustered)
            failures.extend(result_failures)

        return cleaned_results, clustered_results, failures

    with ProcessPoolExecutor(
        max_workers=workers,
        mp_context=mp.get_context("spawn"),
    ) as executor:
        futures = [
            executor.submit(
                process_record,
                record_idx,
                record,
                str(project_root),
                str(results_dir),
                cleaner_specs,
                clusterer_specs,
                cluster_trials,
                clean_state,
                fail_fast,
            )
            for record_idx, record in record_items
        ]

        for future in futures:
            try:
                result_cleaned, result_clustered, result_failures = future.result()
                cleaned_results.extend(result_cleaned)
                clustered_results.extend(result_clustered)
                failures.extend(result_failures)
            except Exception as exc:
                message = f"Record processing failed: {exc}"
                print(f"[ERROR] {message}", flush=True)

                failures.append(
                    {
                        "stage": "record",
                        "message": message,
                    }
                )

                if fail_fast:
                    raise

    return cleaned_results, clustered_results, failures


def build_manifest(
    *,
    args: argparse.Namespace,
    registry_path: Path,
    project_root: Path,
    results_dir: Path,
    eigenvectors_path: Path,
    cleaned_results_path: Path,
    clustered_results_path: Path,
    analyzed_results_path: Path,
    cleaner_specs: list[RuntimeSpec],
    clusterer_specs: list[RuntimeSpec],
    record_count_loaded: int,
    record_count_selected: int,
    cleaned_count: int,
    clustered_count: int,
    failure_count: int,
    runtime_sec: float,
) -> dict[str, Any]:
    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "project_root": str(project_root),
        "methods_config": str(registry_path),
        "results_dir": str(results_dir),
        "eigenvectors_path": str(eigenvectors_path),
        "cleaned_results_path": str(cleaned_results_path),
        "clustered_results_path": str(clustered_results_path),
        "analyzed_results_path": str(analyzed_results_path),
        "selected_cleaners": [
            {
                "name": spec["name"],
                "id": spec["id"],
                "legacy_id": spec["legacy_id"],
                "display_name": spec.get("display_name"),
            }
            for spec in cleaner_specs
        ],
        "selected_clusterers": [
            {
                "name": spec["name"],
                "id": spec["id"],
                "legacy_id": spec["legacy_id"],
                "display_name": spec.get("display_name"),
            }
            for spec in clusterer_specs
        ],
        "max_records": args.max_records,
        "record_offset": args.record_offset,
        "workers": args.workers,
        "cluster_trials": args.cluster_trials,
        "clean_state": args.clean_state,
        "skip_analysis": bool(args.skip_analysis),
        "fail_fast": bool(args.fail_fast),
        "record_count_loaded": record_count_loaded,
        "record_count_selected": record_count_selected,
        "cleaned_result_count": cleaned_count,
        "clustered_result_count": clustered_count,
        "failure_count": failure_count,
        "runtime_sec": runtime_sec,
    }


def main() -> None:
    args = parse_args()
    start_time = time.perf_counter()

    project_root = args.project_root.resolve()
    results_dir = args.results_dir.resolve()
    results_dir.mkdir(parents=True, exist_ok=True)

    registry = load_registry(project_root, args.methods_config)
    registry_path = method_registry_path(project_root, args.methods_config)

    eigenvectors_path = args.eigenvectors.resolve()
    cleaned_results_path = (
        args.cleaned_results.resolve()
        if args.cleaned_results
        else results_dir / "cleaned_results.json"
    )
    clustered_results_path = (
        args.clustered_results.resolve()
        if args.clustered_results
        else results_dir / "clustered_results.json"
    )
    analyzed_results_path = (
        args.analyzed_results.resolve()
        if args.analyzed_results
        else results_dir / "analyzed_results.json"
    )
    manifest_path = (
        args.manifest.resolve()
        if args.manifest
        else results_dir / "logs" / "pipeline_run_manifest.json"
    )
    failures_path = results_dir / "logs" / "pipeline_failures.json"

    cleaner_specs = resolve_runtime_specs(registry, "cleaners", args.cleaners)
    clusterer_specs = resolve_runtime_specs(registry, "clusterers", args.clusterers)

    print(f"[TRACE] Project root: {project_root}")
    print(f"[TRACE] Methods config: {registry_path}")
    print(f"[TRACE] Eigenvectors: {eigenvectors_path}")
    print(f"[TRACE] Results directory: {results_dir}")
    print(
        "[TRACE] Cleaners: "
        + ", ".join(
            f"{spec['name']}(id={spec['id']}, legacy_id={spec['legacy_id']})"
            for spec in cleaner_specs
        )
    )
    print(
        "[TRACE] Clusterers: "
        + ", ".join(
            f"{spec['name']}(id={spec['id']}, legacy_id={spec['legacy_id']})"
            for spec in clusterer_specs
        )
    )

    if args.cluster_trials is not None:
        print(f"[TRACE] Cluster trial budget: {args.cluster_trials}")

    if not eigenvectors_path.exists():
        print(f"[ERROR] Missing eigenvectors file: {eigenvectors_path}")
        print("[ERROR] Run src.pipeline.preprocess first.")
        return

    all_records = read_json(eigenvectors_path)
    if not isinstance(all_records, list):
        print(f"[ERROR] eigenvectors.json must contain a list: {eigenvectors_path}")
        return

    if not all_records:
        print("[ERROR] eigenvectors.json is empty.")
        return

    record_items = build_record_items(
        all_records=all_records,
        record_offset=max(0, int(args.record_offset)),
        max_records=args.max_records,
    )

    if args.max_records is not None:
        print(f"[TRACE] Limit records: max_records={args.max_records}")
    if args.record_offset:
        print(f"[TRACE] Record offset: {args.record_offset}")

    print(f"[TRACE] Loaded records: {len(all_records)}")
    print(f"[TRACE] Selected records: {len(record_items)}")

    workers = max(1, int(args.workers))

    cleaned_results, clustered_results, failures = run_records(
        record_items=record_items,
        project_root=project_root,
        results_dir=results_dir,
        cleaner_specs=cleaner_specs,
        clusterer_specs=clusterer_specs,
        cluster_trials=args.cluster_trials,
        clean_state=args.clean_state,
        workers=workers,
        fail_fast=args.fail_fast,
    )

    write_json(cleaned_results_path, cleaned_results)
    print(f"[TRACE] Cleaned results saved to: {cleaned_results_path}")

    write_json(clustered_results_path, clustered_results)
    print(f"[TRACE] Clustered results saved to: {clustered_results_path}")

    write_json(failures_path, failures)
    if failures:
        print(f"[TRACE] Failure log saved to: {failures_path}")

    if not args.skip_analysis:
        print("[TRACE] Start clustered-result analysis.")
        preprocessing_file_path = project_root / "src" / "pipeline" / "preprocess.py"

        save_analyzed_results(
            preprocessing_file_path=str(preprocessing_file_path),
            eigenvectors_path=str(eigenvectors_path),
            clustered_results_path=str(clustered_results_path),
            output_path=str(analyzed_results_path),
        )

        print(f"[TRACE] Analyzed results saved to: {analyzed_results_path}")
    else:
        print("[TRACE] Analysis skipped by --skip-analysis.")

    runtime_sec = time.perf_counter() - start_time

    manifest = build_manifest(
        args=args,
        registry_path=registry_path,
        project_root=project_root,
        results_dir=results_dir,
        eigenvectors_path=eigenvectors_path,
        cleaned_results_path=cleaned_results_path,
        clustered_results_path=clustered_results_path,
        analyzed_results_path=analyzed_results_path,
        cleaner_specs=cleaner_specs,
        clusterer_specs=clusterer_specs,
        record_count_loaded=len(all_records),
        record_count_selected=len(record_items),
        cleaned_count=len(cleaned_results),
        clustered_count=len(clustered_results),
        failure_count=len(failures),
        runtime_sec=runtime_sec,
    )
    write_json(manifest_path, manifest)
    print(f"[TRACE] Pipeline manifest saved to: {manifest_path}")

    print(
        "[TRACE] Pipeline completed: "
        f"cleaned={len(cleaned_results)}, "
        f"clustered={len(clustered_results)}, "
        f"failures={len(failures)}, "
        f"runtime={runtime_sec:.2f}s"
    )


if __name__ == "__main__":
    main()