#!/usr/bin/env python3
"""Audit legacy figure candidates before migrating plotting code."""

from __future__ import annotations

import argparse
import ast
import csv
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit legacy figure candidate scripts.")
    parser.add_argument(
        "--audit-csv",
        type=Path,
        default=Path("results/processed/legacy_audit_files.csv"),
        help="Legacy audit CSV generated by scripts/29_audit_legacy_sources.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/processed"),
        help="Directory for generated audit outputs.",
    )
    parser.add_argument(
        "--docs-output",
        type=Path,
        default=Path("docs/figure_candidate_details.md"),
        help="Markdown detail report.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Audit CSV not found: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def ast_imports(text: str) -> list[str]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []

    imports: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for item in node.names:
                imports.append(item.name)
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            imports.append(module)

    return sorted(set(imports))


def regex_find(pattern: str, text: str) -> list[str]:
    return sorted(set(match.group(0) for match in re.finditer(pattern, text, flags=re.IGNORECASE)))


def detect_inputs(text: str) -> list[str]:
    patterns = [
        r"pd\.read_csv\([^\n]+",
        r"pandas\.read_csv\([^\n]+",
        r"pd\.read_excel\([^\n]+",
        r"json\.load\([^\n]+",
        r"open\([^\n]+",
        r"np\.load\([^\n]+",
        r"numpy\.load\([^\n]+",
        r"glob\.glob\([^\n]+",
    ]

    hits: list[str] = []
    for pattern in patterns:
        hits.extend(regex_find(pattern, text))

    return hits[:20]


def detect_outputs(text: str) -> list[str]:
    patterns = [
        r"\.savefig\([^\n]+",
        r"plt\.savefig\([^\n]+",
        r"fig\.savefig\([^\n]+",
        r"to_csv\([^\n]+",
        r"to_excel\([^\n]+",
        r"open\([^\n]+[\"']w[\"'][^\n]*",
    ]

    hits: list[str] = []
    for pattern in patterns:
        hits.extend(regex_find(pattern, text))

    return hits[:20]


def detect_plot_calls(text: str) -> list[str]:
    patterns = [
        r"\.plot\(",
        r"plt\.plot\(",
        r"\.scatter\(",
        r"plt\.scatter\(",
        r"\.bar\(",
        r"plt\.bar\(",
        r"\.barh\(",
        r"\.imshow\(",
        r"plt\.imshow\(",
        r"heatmap\(",
        r"radar",
        r"polar",
        r"fill_between\(",
        r"boxplot\(",
        r"hist\(",
        r"networkx",
    ]

    hits: list[str] = []
    for pattern in patterns:
        hits.extend(regex_find(pattern, text))

    return sorted(set(hits))


def infer_figure_type(file_name: str, text: str) -> str:
    lower_name = file_name.lower()
    lower_text = text.lower()

    if "flowchart" in lower_name or "networkx" in lower_text:
        return "workflow_or_diagram"
    if "heat" in lower_name or "heatmap" in lower_text or "imshow" in lower_text:
        return "heatmap"
    if "radar" in lower_name or "polar" in lower_text:
        return "radar"
    if "line" in lower_name or "plt.plot" in lower_text or ".plot(" in lower_text:
        return "line_plot"
    if "point" in lower_name or "scatter" in lower_text:
        return "scatter_or_point"
    if "top10" in lower_name or ".bar(" in lower_text or ".barh(" in lower_text:
        return "bar_chart"
    if "err" in lower_name:
        return "error_analysis_plot"

    return "unknown"


def suggest_target_module(file_name: str, figure_type: str) -> str:
    lower = file_name.lower()

    if "flowchart" in lower:
        return "src/figures/framework_figures.py"
    if "err" in lower or figure_type == "heatmap":
        return "src/figures/data_level_figures.py"
    if "radar" in lower:
        return "src/figures/process_level_figures.py"
    if "cegr" in lower or "score" in lower or "top10" in lower:
        return "src/figures/result_level_figures.py"
    if "hyper" in lower:
        return "src/figures/hyperparameter_figures.py"
    if figure_type == "workflow_or_diagram":
        return "src/figures/framework_figures.py"

    return "src/figures/paper_figures.py"


def suggest_stable_name(file_name: str, figure_type: str) -> str:
    stem = Path(file_name).stem.lower()
    stem = re.sub(r"^[0-9]+[._-]*", "", stem)
    stem = stem.replace("fig_", "")
    stem = stem.replace("plot_", "")
    stem = stem.replace("-", "_")
    stem = re.sub(r"[^a-z0-9_]+", "_", stem)
    stem = re.sub(r"_+", "_", stem).strip("_")

    if not stem:
        stem = figure_type

    return stem


def audit_one(row: dict[str, str]) -> dict[str, Any]:
    legacy_root = Path(row["legacy_root"])
    relative_path = row["relative_path"]
    source_path = legacy_root / relative_path
    file_name = row["file_name"]

    exists = source_path.exists()
    text = read_text(source_path) if exists else ""

    imports = ast_imports(text) if exists else []
    inputs = detect_inputs(text) if exists else []
    outputs = detect_outputs(text) if exists else []
    plot_calls = detect_plot_calls(text) if exists else []
    figure_type = infer_figure_type(file_name, text) if exists else "missing"
    target_module = suggest_target_module(file_name, figure_type)
    stable_name = suggest_stable_name(file_name, figure_type)

    return {
        "legacy_root": str(legacy_root),
        "relative_path": relative_path,
        "file_name": file_name,
        "exists": exists,
        "size_bytes": row.get("size_bytes", ""),
        "figure_type": figure_type,
        "stable_figure_name": stable_name,
        "suggested_target_module": target_module,
        "has_cjk": bool(CJK_RE.search(text)),
        "imports": "; ".join(imports),
        "input_calls": " || ".join(inputs),
        "output_calls": " || ".join(outputs),
        "plot_calls": "; ".join(plot_calls),
        "recommended_action": migration_action(figure_type, target_module),
    }


def migration_action(figure_type: str, target_module: str) -> str:
    if figure_type == "missing":
        return "Skip; source file is missing."
    if figure_type in {"heatmap", "radar", "line_plot", "scatter_or_point", "bar_chart"}:
        return f"Migrate plotting logic into {target_module} after mapping inputs to results/processed or results/tables."
    if figure_type == "workflow_or_diagram":
        return f"Rebuild as a stable framework diagram in {target_module} or document it as a static artifact."
    if figure_type == "error_analysis_plot":
        return f"Migrate after Stage 3 analysis tables expose the required error-level fields."
    return "Review manually before migration."


def write_markdown(path: Path, rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    lines: list[str] = []
    lines.append("# Figure Candidate Detail Audit")
    lines.append("")
    lines.append("This report is generated by `scripts/34_audit_figure_candidates.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Generated at UTC: {summary['generated_at_utc']}")
    lines.append(f"- Figure candidates: {summary['total_candidates']}")
    lines.append("")

    lines.append("### Figure type counts")
    lines.append("")
    lines.append("| Figure type | Count |")
    lines.append("|---|---:|")
    for key, value in summary["figure_type_counts"].items():
        lines.append(f"| {key} | {value} |")
    lines.append("")

    lines.append("## Migration order")
    lines.append("")
    lines.append("Recommended order:")
    lines.append("")
    lines.append("1. Framework and workflow diagrams.")
    lines.append("2. Result-level line or bar plots.")
    lines.append("3. Data-level error heatmaps.")
    lines.append("4. Process-level radar plots.")
    lines.append("5. Any remaining manually reviewed figures.")
    lines.append("")

    lines.append("## Candidate details")
    lines.append("")
    lines.append("| File | Type | Target module | CJK | Recommended action |")
    lines.append("|---|---|---|---:|---|")

    for row in rows:
        lines.append(
            "| "
            + f"{row['relative_path']} | "
            + f"{row['figure_type']} | "
            + f"{row['suggested_target_module']} | "
            + f"{row['has_cjk']} | "
            + f"{row['recommended_action']} |"
        )

    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()

    audit_rows = read_csv_rows(args.audit_csv)
    figure_rows = [row for row in audit_rows if row.get("category") == "figure_candidate"]

    detail_rows = [audit_one(row) for row in figure_rows]

    type_counts = Counter(row["figure_type"] for row in detail_rows)
    target_counts = Counter(row["suggested_target_module"] for row in detail_rows)

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "total_candidates": len(detail_rows),
        "figure_type_counts": dict(sorted(type_counts.items())),
        "target_module_counts": dict(sorted(target_counts.items())),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    detail_csv = args.output_dir / "figure_candidate_details.csv"
    summary_json = args.output_dir / "figure_candidate_summary.json"

    columns = [
        "legacy_root",
        "relative_path",
        "file_name",
        "exists",
        "size_bytes",
        "figure_type",
        "stable_figure_name",
        "suggested_target_module",
        "has_cjk",
        "imports",
        "input_calls",
        "output_calls",
        "plot_calls",
        "recommended_action",
    ]

    write_csv(detail_csv, detail_rows, columns)
    write_json(summary_json, summary)
    write_markdown(args.docs_output, detail_rows, summary)

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print(f"[TRACE] Figure candidate details written to: {detail_csv}")
    print(f"[TRACE] Figure candidate summary written to: {summary_json}")
    print(f"[TRACE] Figure candidate detail report written to: {args.docs_output}")


if __name__ == "__main__":
    main()

