#!/usr/bin/env python3
"""Audit legacy visual-demo candidates before Stage 3 migration."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")

FIGURE_EXTENSIONS = {".png", ".pdf", ".jpg", ".jpeg", ".svg"}
DATA_EXTENSIONS = {".csv", ".json", ".npy", ".npz", ".xlsx", ".xls"}
CODE_EXTENSIONS = {".py", ".ipynb", ".sh"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit legacy visual-demo candidates.")
    parser.add_argument(
        "--audit-csv",
        type=Path,
        default=Path("results/processed/legacy_audit_files.csv"),
        help="Legacy audit CSV generated by scripts/29_audit_legacy_sources.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/processed"),
        help="Directory for generated audit outputs.",
    )
    parser.add_argument(
        "--docs-output",
        type=Path,
        default=Path("docs/visual_demo_migration_plan.md"),
        help="Markdown migration-plan output.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Audit CSV not found: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def sha1_file(path: Path) -> str:
    if not path.exists() or not path.is_file():
        return ""

    h = hashlib.sha1()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    return h.hexdigest()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8-sig", errors="replace")
    except Exception:
        return ""


def classify_visual_demo(path: Path, relative_path: str, file_name: str) -> tuple[str, str]:
    lower = relative_path.lower().replace("\\", "/")
    name = file_name.lower()
    suffix = path.suffix.lower()

    # Highest priority: files explicitly under visual-demo style locations.
    if "visual_demo" in lower or "visual-demo" in lower or "visualdemo" in lower:
        if suffix in CODE_EXTENSIONS:
            return "visual_demo_code", "high"
        if suffix in DATA_EXTENSIONS:
            return "visual_demo_data", "high"
        if suffix in FIGURE_EXTENSIONS:
            return "visual_demo_output", "high"
        return "visual_demo_reference", "high"

    # Paper example figures, especially Figure 1 / Figure 2 style artifacts.
    if any(token in lower for token in ["figure1", "figure_1", "fig1", "fig_1", "figure2", "figure_2", "fig2", "fig_2"]):
        if suffix in FIGURE_EXTENSIONS:
            return "paper_example_figure", "high"
        if suffix in CODE_EXTENSIONS:
            return "paper_example_code", "high"
        if suffix in DATA_EXTENSIONS:
            return "paper_example_data", "high"
        return "paper_example_reference", "medium"

    # Demo scripts and outputs that are not necessarily the paper visual demo.
    if "demo" in name:
        if suffix in CODE_EXTENSIONS:
            return "demo_code_reference", "medium"
        if suffix in FIGURE_EXTENSIONS:
            return "demo_figure_reference", "medium"
        if suffix in DATA_EXTENSIONS:
            return "demo_data_reference", "medium"

    # Example/benchmark demos inside third-party cleaner implementations.
    if any(token in lower for token in ["example", "benchmark", "test.py", "benchmarks"]):
        return "method_example_reference", "low"

    if suffix in FIGURE_EXTENSIONS:
        return "figure_reference", "low"
    if suffix in DATA_EXTENSIONS:
        return "data_reference", "low"
    if suffix in CODE_EXTENSIONS:
        return "code_reference", "low"

    return "other_visual_reference", "low"


def suggested_target(candidate_type: str) -> str:
    mapping = {
        "visual_demo_code": "src/visual_demo/",
        "visual_demo_data": "results/visual_demo/",
        "visual_demo_output": "figures/visual_demo/",
        "visual_demo_reference": "docs/visual_demo.md",
        "paper_example_figure": "figures/visual_demo/",
        "paper_example_code": "src/visual_demo/",
        "paper_example_data": "results/visual_demo/",
        "paper_example_reference": "docs/visual_demo.md",
        "demo_code_reference": "review_manually",
        "demo_figure_reference": "review_manually",
        "demo_data_reference": "review_manually",
        "method_example_reference": "do_not_migrate_to_release",
        "figure_reference": "review_manually",
        "data_reference": "review_manually",
        "code_reference": "review_manually",
    }
    return mapping.get(candidate_type, "review_manually")


def recommended_action(candidate_type: str, priority: str) -> str:
    if candidate_type.startswith("visual_demo") or candidate_type.startswith("paper_example"):
        return "Inspect first; migrate reusable logic into src/visual_demo with English labels and stable output paths."
    if candidate_type == "method_example_reference":
        return "Keep as third-party or method reference only; do not expose as reviewer-facing visual demo."
    if priority == "medium":
        return "Review manually; migrate only if it supports the paper example demo."
    return "Low priority; do not migrate unless needed."


def inspect_file(row: dict[str, str]) -> dict[str, Any]:
    legacy_root = Path(row["legacy_root"])
    relative_path = row["relative_path"]
    source_path = legacy_root / relative_path
    file_name = row["file_name"]
    suffix = source_path.suffix.lower()

    exists = source_path.exists()
    candidate_type, priority = classify_visual_demo(source_path, relative_path, file_name)

    text = read_text(source_path) if exists and suffix in CODE_EXTENSIONS.union({".md", ".txt", ".tex"}) else ""

    input_calls = []
    output_calls = []
    plot_calls = []

    if text:
        for pattern in [
            r"pd\.read_csv\([^\n]+",
            r"pandas\.read_csv\([^\n]+",
            r"pd\.read_excel\([^\n]+",
            r"np\.load\([^\n]+",
            r"open\([^\n]+",
        ]:
            input_calls.extend(match.group(0) for match in re.finditer(pattern, text, flags=re.IGNORECASE))

        for pattern in [
            r"\.savefig\([^\n]+",
            r"plt\.savefig\([^\n]+",
            r"\.to_csv\([^\n]+",
            r"\.to_excel\([^\n]+",
            r"open\([^\n]+[\"']w[\"'][^\n]*",
        ]:
            output_calls.extend(match.group(0) for match in re.finditer(pattern, text, flags=re.IGNORECASE))

        for pattern in [
            r"plt\.scatter\(",
            r"\.scatter\(",
            r"plt\.plot\(",
            r"\.plot\(",
            r"plt\.bar\(",
            r"\.bar\(",
            r"imshow\(",
            r"contour\(",
            r"kmeans",
            r"hierarchical",
            r"cluster",
        ]:
            plot_calls.extend(match.group(0) for match in re.finditer(pattern, text, flags=re.IGNORECASE))

    return {
        "legacy_root": str(legacy_root),
        "relative_path": relative_path,
        "file_name": file_name,
        "exists": exists,
        "extension": suffix,
        "size_bytes": row.get("size_bytes", ""),
        "sha1": sha1_file(source_path) if exists else "",
        "candidate_type": candidate_type,
        "priority": priority,
        "has_cjk": bool(CJK_RE.search(text)),
        "input_calls": " || ".join(sorted(set(input_calls))[:30]),
        "output_calls": " || ".join(sorted(set(output_calls))[:30]),
        "plot_calls": "; ".join(sorted(set(plot_calls))),
        "suggested_target": suggested_target(candidate_type),
        "recommended_action": recommended_action(candidate_type, priority),
    }


def write_markdown(path: Path, rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    high_rows = [row for row in rows if row["priority"] == "high"]
    medium_rows = [row for row in rows if row["priority"] == "medium"]

    lines: list[str] = []
    lines.append("# Visual Demo Migration Plan")
    lines.append("")
    lines.append("This document is generated by `scripts/39_audit_visual_demo.py`.")
    lines.append("")
    lines.append("Stage 3.6 normalizes reviewer-facing visual demo figures.")
    lines.append("")
    lines.append("The visual demo should explain the paper example using stable English labels and reproducible scripts.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Generated at UTC: {summary['generated_at_utc']}")
    lines.append(f"- Total candidates: {summary['total_candidates']}")
    lines.append("")
    lines.append("### Priority counts")
    lines.append("")
    lines.append("| Priority | Count |")
    lines.append("|---|---:|")
    for key, value in summary["priority_counts"].items():
        lines.append(f"| {key} | {value} |")
    lines.append("")
    lines.append("### Candidate type counts")
    lines.append("")
    lines.append("| Candidate type | Count |")
    lines.append("|---|---:|")
    for key, value in summary["candidate_type_counts"].items():
        lines.append(f"| {key} | {value} |")
    lines.append("")
    lines.append("## Migration rules")
    lines.append("")
    lines.append("1. Use `src/visual_demo` for demo data generation and demo plotting code.")
    lines.append("2. Use `results/visual_demo` for generated or archived visual-demo data.")
    lines.append("3. Use `figures/visual_demo` for generated English visual-demo figures.")
    lines.append("4. Do not expose third-party method examples as reviewer-facing visual demos.")
    lines.append("5. Regenerate demo figures from code when possible instead of copying static legacy figures.")
    lines.append("")
    lines.append("## High-priority candidates")
    lines.append("")
    if high_rows:
        lines.append("| File | Type | Target | Recommended action |")
        lines.append("|---|---|---|---|")
        for row in high_rows[:60]:
            lines.append(
                f"| {row['relative_path']} | {row['candidate_type']} | "
                f"{row['suggested_target']} | {row['recommended_action']} |"
            )
    else:
        lines.append("No high-priority visual-demo candidates were found.")
    lines.append("")
    lines.append("## Medium-priority candidates")
    lines.append("")
    if medium_rows:
        lines.append("| File | Type | Target | Recommended action |")
        lines.append("|---|---|---|---|")
        for row in medium_rows[:60]:
            lines.append(
                f"| {row['relative_path']} | {row['candidate_type']} | "
                f"{row['suggested_target']} | {row['recommended_action']} |"
            )
    else:
        lines.append("No medium-priority visual-demo candidates were found.")
    lines.append("")
    lines.append("## Next migration target")
    lines.append("")
    lines.append("Build a small synthetic visual demo that recreates the clean, dirty, cleaned, and clustered comparison with English labels.")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    audit_rows = read_csv_rows(args.audit_csv)
    visual_rows = [row for row in audit_rows if row.get("category") == "visual_demo_candidate"]

    details = [inspect_file(row) for row in visual_rows]

    candidate_type_counts = Counter(row["candidate_type"] for row in details)
    priority_counts = Counter(row["priority"] for row in details)
    target_counts = Counter(row["suggested_target"] for row in details)

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "total_candidates": len(details),
        "candidate_type_counts": dict(sorted(candidate_type_counts.items())),
        "priority_counts": dict(sorted(priority_counts.items())),
        "target_counts": dict(sorted(target_counts.items())),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    details_csv = args.output_dir / "visual_demo_details.csv"
    summary_json = args.output_dir / "visual_demo_summary.json"

    columns = [
        "legacy_root",
        "relative_path",
        "file_name",
        "exists",
        "extension",
        "size_bytes",
        "sha1",
        "candidate_type",
        "priority",
        "has_cjk",
        "input_calls",
        "output_calls",
        "plot_calls",
        "suggested_target",
        "recommended_action",
    ]

    write_csv(details_csv, details, columns)
    write_json(summary_json, summary)
    write_markdown(args.docs_output, details, summary)

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print(f"[TRACE] Visual-demo details written to: {details_csv}")
    print(f"[TRACE] Visual-demo summary written to: {summary_json}")
    print(f"[TRACE] Visual-demo migration plan written to: {args.docs_output}")


if __name__ == "__main__":
    main()

