#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Paper-level TRACE Stage 4 reproduction entrypoint.

Reviewer-facing entrypoint for reproducing the TRACE leave-one-dataset-out
validation reported in the paper.

Default behavior is intentionally result-focused:

1. verify or build the base Stage-4 replay ledger;
2. run leave-one-dataset-out TRACE validation;
3. write a manifest and a compact report;
4. optionally pack the paper-exact outputs.

The script does not rerun cleaning or clustering by default. The expected input
is the cached-cleaning clustering replay directory, normally:

    results/trace_cluster_replay_all

Typical Linux use:

    python -u scripts/39_run_trace_stage4_paper_repro.py \
      --results-dir results/trace_cluster_replay_all \
      --config configs/trace.yaml \
      --output-dir results/processed/trace/lodo_paper_repro \
      --random-seeds 1000 \
      --seed 20260424 \
      --skip-existing \
      --pack \
      --log \
      --quiet

With ``--quiet``, the terminal and the saved log show only high-level progress
and the final JSON summary. Verbose child-script output is suppressed so the log
is reviewer-friendly and not dominated by intermediate fold outputs.

Figures are not regenerated by default. Use ``--make-figures`` when figure
regeneration is desired; figure drawing is maintained in
``scripts/37_plot_trace_validation.py``.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tarfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


DEFAULT_EXPECTED = {
    "median_trace_hit95_progress": 0.1348,
    "median_blind_random_hit95_progress": 0.2701,
    "median_trace_auc_retention": 0.9824,
    "median_blind_random_auc_retention": 0.9537,
}


class ProgressLogger:
    """Write the same reviewer-facing progress stream to terminal and log."""

    def __init__(self, log_path: Path | None = None) -> None:
        self.log_path = log_path
        self._fh = None
        if log_path is not None:
            log_path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = log_path.open("w", encoding="utf-8")

    def write(self, message: str = "") -> None:
        print(message, flush=True)
        if self._fh is not None:
            self._fh.write(message + "\n")
            self._fh.flush()

    def write_json(self, data: dict[str, Any]) -> None:
        text = json.dumps(data, indent=2, ensure_ascii=False)
        self.write(text)

    def close(self) -> None:
        if self._fh is not None:
            self._fh.close()
            self._fh = None



def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[1]



def rel_or_abs(path: Path, root: Path) -> Path:
    return path if path.is_absolute() else root / path



def format_cmd(cmd: Iterable[str]) -> str:
    return " ".join(str(x) for x in cmd)



def run_step(
    cmd: list[str],
    *,
    cwd: Path,
    logger: ProgressLogger,
    label: str,
    quiet: bool,
) -> None:
    """Run a subprocess.

    In quiet/reviewer mode, child stdout/stderr is captured and suppressed.
    The compact progress log records only high-level stages. If a child fails,
    the last lines of captured output are printed to help debugging.
    """
    if quiet:
        logger.write(f"[TRACE-STAGE4] {label} ...")
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        if proc.returncode != 0:
            logger.write(f"[TRACE-STAGE4] {label} failed with exit code {proc.returncode}.")
            tail = "\n".join((proc.stdout or "").splitlines()[-40:])
            if tail:
                logger.write("[TRACE-STAGE4] Last captured child output:")
                logger.write(tail)
            raise subprocess.CalledProcessError(proc.returncode, cmd)
        logger.write(f"[TRACE-STAGE4] {label} done.")
        return

    logger.write(f"[TRACE-STAGE4] {label} ...")
    logger.write("[TRACE-STAGE4] $ " + format_cmd(cmd))
    subprocess.run(cmd, cwd=str(cwd), check=True)
    logger.write(f"[TRACE-STAGE4] {label} done.")



def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8-sig") as f:
        return json.load(f)



def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)



def git_commit(root: Path) -> str | None:
    try:
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=str(root), text=True).strip()
        return out or None
    except Exception:
        return None



def has_full_trace_outputs(base_trace_output_dir: Path) -> bool:
    required = [
        "trace_dataset_summary.csv",
        "trace_replay_trials.csv",
        "trace_path_decisions.csv",
        "trace_baseline_sequence.csv",
        "trace_aggregate_summary.json",
    ]
    return all((base_trace_output_dir / name).exists() for name in required)



def has_lodo_outputs(output_dir: Path) -> bool:
    required = [
        "lodo_aggregate_summary.json",
        "lodo_folds.csv",
        "lodo_blind_random_dataset_summary.csv",
    ]
    return all((output_dir / name).exists() for name in required)



def metric_checks(aggregate: dict[str, Any], tolerance: float) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for key, expected in DEFAULT_EXPECTED.items():
        actual_raw = aggregate.get(key)
        try:
            actual = float(actual_raw)
            diff = abs(actual - expected)
            ok = diff <= tolerance
        except Exception:
            actual = None
            diff = None
            ok = False
        rows.append({
            "metric": key,
            "expected_reference": expected,
            "actual": actual,
            "abs_diff": diff,
            "within_tolerance": ok,
        })
    return rows



def write_report(path: Path, manifest: dict[str, Any]) -> None:
    agg = manifest.get("aggregate", {})
    checks = manifest.get("metric_checks", [])
    figures_generated = bool(manifest.get("figures_generated"))
    lines = [
        "# TRACE Stage 4 paper-level reproduction report",
        "",
        "This report is generated by `scripts/39_run_trace_stage4_paper_repro.py`.",
        "It reproduces the leave-one-dataset-out TRACE validation used in the paper.",
        "",
        "## Main results",
        "",
        f"- Number of held-out corrupted instances: `{agg.get('n_datasets', 'NA')}`",
        f"- TRACE median hit-to-95% progress: `{agg.get('median_trace_hit95_progress', 'NA')}`",
        f"- Blind-random median hit-to-95% progress: `{agg.get('median_blind_random_hit95_progress', 'NA')}`",
        f"- TRACE median AUC retention: `{agg.get('median_trace_auc_retention', 'NA')}`",
        f"- Blind-random median AUC retention: `{agg.get('median_blind_random_auc_retention', 'NA')}`",
        "",
        "## Metric checks against paper reference values",
        "",
        "| Metric | Expected reference | Actual | Absolute diff | Within tolerance |",
        "|---|---:|---:|---:|:---:|",
    ]
    for row in checks:
        lines.append(
            f"| {row['metric']} | {row['expected_reference']} | {row['actual']} | "
            f"{row['abs_diff']} | {row['within_tolerance']} |"
        )
    lines.extend([
        "",
        "## Outputs",
        "",
        "- `lodo_aggregate_summary.json`",
        "- `lodo_folds.csv`",
        "- `lodo_blind_random_dataset_summary.csv`",
        "- `trace_stage4_manifest.json`",
        "- `trace_stage4_repro_report.md`",
    ])
    if figures_generated:
        lines.extend([
            "- `figures/lodo_hit95_progress_ecdf.pdf`",
            "- `figures/lodo_auc_retention_ecdf.pdf`",
        ])
    else:
        lines.append("- Figures were not regenerated in this run; use `--make-figures` to do so.")
    lines.extend([
        "",
        "Full clustering trial logs are intentionally not packed here because they are large.",
        "The reproduction uses the cached-cleaning clustering replay directory supplied via `--results-dir`.",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")



def copy_lodo_alias_figures(output_dir: Path) -> None:
    fig_dir = output_dir / "figures"
    aliases = [
        ("hit95_progress_ecdf.pdf", "lodo_hit95_progress_ecdf.pdf"),
        ("hit95_progress_ecdf.png", "lodo_hit95_progress_ecdf.png"),
        ("auc_retention_ecdf.pdf", "lodo_auc_retention_ecdf.pdf"),
        ("auc_retention_ecdf.png", "lodo_auc_retention_ecdf.png"),
    ]
    for src_name, dst_name in aliases:
        src = fig_dir / src_name
        dst = fig_dir / dst_name
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)



def pack_outputs(output_dir: Path, pack_path: Path, *, include_figures: bool) -> None:
    pack_path.parent.mkdir(parents=True, exist_ok=True)
    allowed = [
        "lodo_aggregate_summary.json",
        "lodo_folds.csv",
        "lodo_blind_random_dataset_summary.csv",
        "lodo_trace_dataset_summary.csv",
        "trace_stage4_manifest.json",
        "trace_stage4_repro_report.md",
    ]
    with tarfile.open(pack_path, "w:gz") as tar:
        for name in allowed:
            p = output_dir / name
            if p.exists():
                tar.add(p, arcname=f"trace_stage4_paper_exact/{name}")
        if include_figures:
            fig_dir = output_dir / "figures"
            if fig_dir.exists():
                for p in fig_dir.glob("*.pdf"):
                    tar.add(p, arcname=f"trace_stage4_paper_exact/figures/{p.name}")
        log_dir = output_dir / "logs"
        if log_dir.exists():
            for p in log_dir.glob("*.log"):
                tar.add(p, arcname=f"trace_stage4_paper_exact/logs/{p.name}")



def main() -> int:
    parser = argparse.ArgumentParser(description="Run paper-level TRACE Stage 4 LODO reproduction.")
    parser.add_argument("--project-root", type=Path, default=None)
    parser.add_argument("--results-dir", type=Path, default=Path("results/trace_cluster_replay_all"))
    parser.add_argument("--base-trace-output-dir", type=Path, default=Path("results/processed/trace/cluster_replay_all"))
    parser.add_argument("--config", type=Path, default=Path("configs/trace.yaml"))
    parser.add_argument("--output-dir", type=Path, default=Path("results/processed/trace/lodo_paper_repro"))
    parser.add_argument("--random-seeds", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=20260424)
    parser.add_argument("--budgets", type=float, nargs="*", default=[0.01, 0.02, 0.05, 0.10, 0.20])
    parser.add_argument("--rebuild-base", action="store_true", help="Re-run scripts/30_replay_trace.py for the base full trace output.")
    parser.add_argument("--skip-existing", action="store_true", help="Pass --skip-existing to LODO validation and reuse completed folds.")
    parser.add_argument("--skip-lodo", action="store_true", help="Do not run LODO; only write manifest/report from existing outputs.")
    parser.add_argument("--make-figures", action="store_true", help="Regenerate TRACE validation figures via scripts/37_plot_trace_validation.py. Disabled by default.")
    parser.add_argument("--skip-figures", action="store_true", help="Deprecated compatibility flag; figures are skipped unless --make-figures is used.")
    parser.add_argument("--pack", action="store_true", help="Pack a small paper-exact tarball after reproduction.")
    parser.add_argument("--pack-path", type=Path, default=Path("artifacts/trace_stage4_paper_exact.tgz"))
    parser.add_argument("--strict-metrics", action="store_true", help="Fail if final metrics differ from paper reference values beyond tolerance.")
    parser.add_argument("--tolerance", type=float, default=0.02)
    parser.add_argument("--log", action="store_true", help="Save the compact reviewer-facing progress stream under <output-dir>/logs.")
    parser.add_argument("--quiet", action="store_true", help="Show high-level progress and final JSON only; suppress verbose child-script output.")
    args = parser.parse_args()

    project_root = rel_or_abs(args.project_root, Path.cwd()).resolve() if args.project_root else repo_root_from_script().resolve()
    results_dir = rel_or_abs(args.results_dir, project_root).resolve()
    base_trace_output_dir = rel_or_abs(args.base_trace_output_dir, project_root).resolve()
    config_path = rel_or_abs(args.config, project_root).resolve()
    output_dir = rel_or_abs(args.output_dir, project_root).resolve()
    pack_path = rel_or_abs(args.pack_path, project_root).resolve()

    start = time.time()
    output_dir.mkdir(parents=True, exist_ok=True)

    log_path = None
    if args.log:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        log_path = output_dir / "logs" / f"trace_stage4_paper_repro_compact_{timestamp}.log"

    logger = ProgressLogger(log_path=log_path)
    try:
        logger.write("[TRACE-STAGE4] Paper-level TRACE LODO reproduction")
        logger.write(f"[TRACE-STAGE4] Project root: {project_root}")
        logger.write(f"[TRACE-STAGE4] Results dir: {results_dir}")
        logger.write(f"[TRACE-STAGE4] Output dir: {output_dir}")
        if log_path is not None:
            logger.write(f"[TRACE-STAGE4] Compact log: {log_path}")

        if not results_dir.exists():
            raise FileNotFoundError(f"Missing results dir: {results_dir}")
        if not config_path.exists():
            raise FileNotFoundError(f"Missing TRACE config: {config_path}")

        py = sys.executable

        if args.rebuild_base or not has_full_trace_outputs(base_trace_output_dir):
            run_step([
                py, str(project_root / "scripts" / "30_replay_trace.py"),
                "--project-root", str(project_root),
                "--results-dir", str(results_dir),
                "--config", str(config_path),
                "--output-dir", str(base_trace_output_dir),
            ], cwd=project_root, logger=logger, label="Step 1/4: build base TRACE replay ledger", quiet=args.quiet)
        else:
            logger.write("[TRACE-STAGE4] Step 1/4: base TRACE replay ledger found; skipping rebuild.")

        if not args.skip_lodo:
            cmd = [
                py, str(project_root / "scripts" / "38_lodo_trace_validation.py"),
                "--project-root", str(project_root),
                "--results-dir", str(results_dir),
                "--base-trace-output-dir", str(base_trace_output_dir),
                "--config", str(config_path),
                "--output-dir", str(output_dir),
                "--random-seeds", str(args.random_seeds),
                "--seed", str(args.seed),
                "--budgets", *[str(x) for x in args.budgets],
            ]
            if args.skip_existing:
                cmd.append("--skip-existing")
            run_step(cmd, cwd=project_root, logger=logger, label="Step 2/4: run leave-one-dataset-out replay", quiet=args.quiet)
        else:
            logger.write("[TRACE-STAGE4] Step 2/4: LODO replay skipped; using existing outputs.")

        if not has_lodo_outputs(output_dir):
            raise FileNotFoundError(f"LODO outputs incomplete in: {output_dir}")

        figures_generated = bool(args.make_figures and not args.skip_figures)
        if figures_generated:
            run_step([
                py, str(project_root / "scripts" / "37_plot_trace_validation.py"),
                "--lodo-dir", str(output_dir),
                "--out-dir", str(output_dir / "figures"),
            ], cwd=project_root, logger=logger, label="Step 3/4: regenerate figures", quiet=args.quiet)
            copy_lodo_alias_figures(output_dir)
        else:
            logger.write("[TRACE-STAGE4] Step 3/4: figure generation skipped; use --make-figures to regenerate figures.")

        aggregate_path = output_dir / "lodo_aggregate_summary.json"
        aggregate = read_json(aggregate_path)
        checks = metric_checks(aggregate, args.tolerance)
        all_ok = all(bool(row["within_tolerance"]) for row in checks)

        manifest = {
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "project_root": str(project_root),
            "git_commit": git_commit(project_root),
            "results_dir": str(results_dir),
            "base_trace_output_dir": str(base_trace_output_dir),
            "output_dir": str(output_dir),
            "config": str(config_path),
            "random_seeds": args.random_seeds,
            "seed": args.seed,
            "budgets": args.budgets,
            "figures_generated": figures_generated,
            "aggregate": aggregate,
            "metric_checks": checks,
            "metric_check_tolerance": args.tolerance,
            "metric_checks_all_within_tolerance": all_ok,
            "elapsed_seconds": time.time() - start,
        }
        manifest_path = output_dir / "trace_stage4_manifest.json"
        report_path = output_dir / "trace_stage4_repro_report.md"
        write_json(manifest_path, manifest)
        write_report(report_path, manifest)
        logger.write("[TRACE-STAGE4] Step 4/4: manifest and report written.")

        summary = {
            "output_dir": str(output_dir),
            "manifest": str(manifest_path),
            "report": str(report_path),
            "pack_path": str(pack_path) if args.pack else None,
            "metric_checks_all_within_tolerance": all_ok,
            "aggregate": {
                k: aggregate.get(k) for k in [
                    "n_datasets",
                    "median_trace_hit95_progress",
                    "median_blind_random_hit95_progress",
                    "median_trace_auc_retention",
                    "median_blind_random_auc_retention",
                ]
            },
        }

        if args.pack:
            logger.write(f"[TRACE-STAGE4] Packing paper-exact artifact: {pack_path}")

        # Keep the final reviewer-facing result as the last terminal/log block.
        logger.write_json(summary)

        if args.pack:
            pack_outputs(output_dir, pack_path, include_figures=figures_generated)

        if args.strict_metrics and not all_ok:
            logger.write("[TRACE-STAGE4] Metric check failed under --strict-metrics.")
            return 2
        return 0
    finally:
        logger.close()


if __name__ == "__main__":
    raise SystemExit(main())
