#!/usr/bin/env python3
"""Audit selected paper table and analysis scripts for Mode A generated replay."""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

TRACE_PROJECT_ROOT = Path(
    os.environ.get("TRACE_PROJECT_ROOT", Path(__file__).resolve().parents[1])
).resolve()

if str(TRACE_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(TRACE_PROJECT_ROOT))

from src.paper_replay.workbook_utils import sha256_file, write_json


SCRIPT_GROUPS = {"paper_table_scripts", "analysis_scripts"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit paper table scripts selected for Mode A replay.")
    parser.add_argument(
        "--archive-manifest",
        type=Path,
        default=Path("analysis/paper_exact/mode_a_paper_exact_archive_manifest.json"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("analysis/paper_generated"),
    )
    return parser.parse_args()


def read_manifest(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Archive manifest not found: {path}")
    return json.loads(path.read_text(encoding="utf-8-sig"))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def find_regex(pattern: str, text: str) -> list[str]:
    return sorted(set(re.findall(pattern, text, flags=re.IGNORECASE)))[:50]


def inspect_script(path: Path) -> dict:
    text = read_text(path)

    input_calls = []
    output_calls = []

    input_patterns = [
        r"read_csv\([^\n]+",
        r"read_excel\([^\n]+",
        r"load_workbook\([^\n]+",
        r"json\.load\([^\n]+",
        r"open\([^\n]+",
    ]

    output_patterns = [
        r"to_csv\([^\n]+",
        r"to_excel\([^\n]+",
        r"savefig\([^\n]+",
        r"json\.dump\([^\n]+",
        r"Workbook\(",
    ]

    for pattern in input_patterns:
        input_calls.extend(find_regex(pattern, text))

    for pattern in output_patterns:
        output_calls.extend(find_regex(pattern, text))

    literal_paths = find_regex(
        r"""["'][^"']+\.(?:csv|xlsx|xls|json|png|pdf|txt)["']""",
        text,
    )

    return {
        "input_calls": " || ".join(sorted(set(input_calls))[:30]),
        "output_calls": " || ".join(sorted(set(output_calls))[:30]),
        "literal_paths": " || ".join(literal_paths[:40]),
        "line_count": len(text.splitlines()),
    }


def write_csv(path: Path, rows: list[dict], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path: Path, rows: list[dict], summary: dict) -> None:
    lines = [
        "# Paper Table Script Audit",
        "",
        "This document is generated by `scripts/50_audit_paper_table_scripts.py`.",
        "",
        f"- Generated at UTC: {summary['generated_at_utc']}",
        f"- Script count: {summary['script_count']}",
        "",
        "## Group counts",
        "",
        "| Group | Count |",
        "|---|---:|",
    ]

    for group, count in sorted(summary["group_counts"].items()):
        lines.append(f"| {group} | {count} |")

    lines += [
        "",
        "## Scripts",
        "",
        "| Group | File | Inputs detected | Outputs detected |",
        "|---|---|---|---|",
    ]

    for row in rows:
        lines.append(
            f"| {row['selection_group']} | {row['replay_path']} | "
            f"{row['input_calls'][:120]} | {row['output_calls'][:120]} |"
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    manifest = read_manifest(args.archive_manifest)

    rows = []
    for item in manifest.get("copied", []):
        if item.get("selection_group") not in SCRIPT_GROUPS:
            continue

        replay_path = Path(item.get("replay_path", ""))
        archive_path = Path(item.get("archive_path", ""))

        script_path = replay_path if replay_path.exists() else archive_path
        if not script_path.exists():
            continue

        info = inspect_script(script_path)

        rows.append({
            "selection_group": item.get("selection_group", ""),
            "category": item.get("category", ""),
            "source": item.get("source", ""),
            "archive_path": str(archive_path),
            "replay_path": str(replay_path),
            "file_name": script_path.name,
            "line_count": info["line_count"],
            "sha256": sha256_file(script_path),
            "input_calls": info["input_calls"],
            "output_calls": info["output_calls"],
            "literal_paths": info["literal_paths"],
        })

    rows = sorted(rows, key=lambda r: (r["selection_group"], r["file_name"]))

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "archive_manifest": str(args.archive_manifest),
        "script_count": len(rows),
        "group_counts": dict(Counter(row["selection_group"] for row in rows)),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)

    columns = [
        "selection_group",
        "category",
        "source",
        "archive_path",
        "replay_path",
        "file_name",
        "line_count",
        "sha256",
        "input_calls",
        "output_calls",
        "literal_paths",
    ]

    out_csv = args.output_dir / "table_script_audit.csv"
    out_json = args.output_dir / "table_script_audit.json"
    out_md = args.output_dir / "table_script_audit.md"

    write_csv(out_csv, rows, columns)
    write_json(out_json, {"summary": summary, "scripts": rows})
    write_markdown(out_md, rows, summary)

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print(f"[TRACE] Paper table script audit written to: {out_csv}")
    print(f"[TRACE] Paper table script audit report written to: {out_md}")


if __name__ == "__main__":
    main()

